### ISSUE TITLE
code of Fig. 1. Visualization

### ISSUE THREAD

**Issue by dana-niu** [fanrena/DPT#1]
hello
Can you provide the relevant code of Fig. 1. Visualization for learning?
Sincerely look forward to your reply.

**Comment by fanrena** [comment]
Sorry that I can`t offer a click-and-run visualization code because the code is completely mixed with other codes.

The visualization code I adopted is rather easy to implement and the core code of the visualization looks like this:

```python
with open("./attn_map.json", "r") as f:
    data = json.load(f)["attn_map"]
    
img = cv2.imread(f'your path'+path)
img = cv2.resize(img, (224, 224))

attn_weight = np.array(attn_weight)
attn_weight = min_max(attn_weight)
attn_weight=attn_weight*255.0
attn_weight.resize(7,7)
newimg = cv2.resize(attn_weight.astype('uint8'), (224, 224))

heat_map = cv2.applyColorMap(newimg.astype('uint8'), cv2.COLORMAP_JET)
heat_map = 0.7*heat_map + 0.3*img
if path in save_list:
    mkdir_if_missing(f'./visualize_pic/processed/{dataset}/{image_name}/')
    cv2.imwrite(f'./visualize_pic/processed/{dataset}/{image_name}/{t}_{ans}_{label}.jpg', heat_map)
```

The code is based on the precomputed and stored attention map in attn_map.json file. Thus you need to precompute the attention map and store them. The image path can be obtained by parse batch like this
```python
impath = batch["impath"]
```
The attention map of MultiheadAttention in CLIP is not returned by default. It will be something like this.
```python
return self.attn(x, x, x, need_weights=False, attn_mask=self.attn_mask)[0]
```
So check out the clip code if you have a problem with obtaining an attention map. See [Here](https://pytorch.org/docs/stable/generated/torch.nn.MultiheadAttention.html) for more details.

But I should remind you that the visualization of the CLIP model only works for ViT-B/32. When it comes to the ViT-B/16 or larger vision transformer models. The attention map would be disrupted by artifacts. See [Vision Transformers need Registers](https://arxiv.org/abs/2309.16588) for more details about the artifacts.

**Comment by fanrena** [comment]
I`m closing the issue. Feel free to reopen it if you have more problems with visualization.

**Comment by dana-niu** [comment]
Thank you very much for your reply.
Your reply was very helpful.
I will try and learn.
